controllers:
    resource: ../src/Controller/
    type: annotation

user:
    resource: ../src/Characters/Infrastructure/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
