controllers:
    resource: ../src/Controller/
    type: annotation

characters:
    resource: ../src/Characters/Infrastructure/Controller/
    type: annotation

movies:
    resource: ../src/Movies/Infrastructure/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
